from fastapi import APIRouter

from app.api import agent, ai, alerts, audit, auth_upstox, automation, backtest, bootstrap, candles, chart, controls, data_pipeline, instruments, intraday, learning, market, metrics, news, orders, orders_state, paper, patterns, portfolio, positions, prediction, realtime, recommendations, safety, smart_search, strategy, trade, trade_state, universe, upstox, watchlist, ws

api_router = APIRouter(prefix="/api")

api_router.include_router(candles.router, tags=["candles"])
api_router.include_router(intraday.router, tags=["intraday"])
api_router.include_router(chart.router, tags=["chart"])
api_router.include_router(ai.router, tags=["ai"])
api_router.include_router(instruments.router, tags=["instruments"])
api_router.include_router(strategy.router, tags=["strategy"])
api_router.include_router(backtest.router, tags=["backtest"])
api_router.include_router(recommendations.router, tags=["recommendations"])
api_router.include_router(smart_search.router, tags=["smart-search"])
api_router.include_router(trade.router, tags=["trade"])
api_router.include_router(trade_state.router, tags=["trade-state"])
api_router.include_router(portfolio.router, tags=["portfolio"])
api_router.include_router(paper.router, tags=["paper"])
api_router.include_router(market.router, tags=["market"])
api_router.include_router(safety.router, tags=["safety"])
api_router.include_router(controls.router, tags=["controls"])
api_router.include_router(ws.router, tags=["ws"])
api_router.include_router(realtime.router, tags=["realtime"])
api_router.include_router(auth_upstox.router, tags=["auth"])
api_router.include_router(upstox.router, tags=["upstox"])
api_router.include_router(orders.router, tags=["orders"])
api_router.include_router(orders_state.router, tags=["orders"])
api_router.include_router(learning.router, tags=["learning"])
api_router.include_router(patterns.router, tags=["patterns"])
api_router.include_router(bootstrap.router, tags=["bootstrap"])
api_router.include_router(audit.router, tags=["audit"])
api_router.include_router(watchlist.router, tags=["watchlist"])
api_router.include_router(news.router, tags=["news"])
api_router.include_router(alerts.router, tags=["alerts"])
api_router.include_router(universe.router, tags=["universe"])
api_router.include_router(agent.router, tags=["agent"])
api_router.include_router(data_pipeline.router, tags=["data"])
api_router.include_router(automation.router, tags=["automation"])
api_router.include_router(prediction.router, tags=["prediction"])
api_router.include_router(positions.router, tags=["positions"])
api_router.include_router(metrics.router, tags=["metrics"])
